In [1]:
import pandas as pd
data = pd.read_csv("MinorityTransformed500.csv")
print data.shape
data[:10]

(51671, 18)

,Unnamed: 0,display_id,ad_id,clicked,landing_page,campaign_id,advertiser_id,uuid,document_id,platform,geo_location,day,hour,category_id,topic_id,entity_id,source_id,publisher_id
0,0,1459,132913,0,MinorityClass,MinorityClass,3074,faf57f287517f4,1649164,2,CA,2016-06-14,4,1610.0,16.0,MinorityClass,MinorityClass,MinorityClass
1,1,1459,176834,0,1145458,MinorityClass,2352,faf57f287517f4,1649164,2,CA,2016-06-14,4,1610.0,16.0,MinorityClass,MinorityClass,MinorityClass
2,2,1459,206927,1,MinorityClass,MinorityClass,2635,faf57f287517f4,1649164,2,CA,2016-06-14,4,1610.0,16.0,MinorityClass,MinorityClass,MinorityClass
3,3,1820,45305,0,MinorityClass,MinorityClass,1198,1f73468d752afe,1764575,2,IL,2016-06-14,4,1907.0,184.0,MinorityClass,MinorityClass,MinorityClass
4,4,1820,97384,1,MinorityClass,MinorityClass,1644,1f73468d752afe,1764575,2,IL,2016-06-14,4,1907.0,184.0,MinorityClass,MinorityClass,MinorityClass
5,5,1820,211049,0,1534322,24127,1863,1f73468d752afe,1764575,2,IL,2016-06-14,4,1907.0,184.0,MinorityClass,MinorityClass,MinorityClass
6,6,1820,250319,0,1592795,25645,2348,1f73468d752afe,1764575,2,IL,2016-06-14,4,1907.0,184.0,MinorityClass,MinorityClass,MinorityClass
7,7,2614,67347,0,942989,9029,92,2180e7affabb67,341873,3,OH,2016-06-14,4,1513.0,MinorityClass,Unknown,MinorityClass,MinorityClass
8,8,2614,144740,0,1337362,18488,2909,2180e7affabb67,341873,3,OH,2016-06-14,4,1513.0,MinorityClass,Unknown,MinorityClass,MinorityClass
9,9,2614,148962,0,1340766,MinorityClass,3016,2180e7affabb67,341873,3,OH,2016-06-14,4,1513.0,MinorityClass,Unknown,MinorityClass,MinorityClass

In [2]:
data.T.apply(lambda x: x.nunique(), axis=1)

Unnamed: 0       51671
display_id        9994
ad_id            17547
clicked              2
landing_page       501
campaign_id        501
advertiser_id      501
uuid              9993
document_id       7317
platform             3
geo_location        55
day                 14
hour                24
category_id         21
topic_id            21
entity_id           21
source_id           21
publisher_id        21
dtype: int64

In [3]:
# Dropping unnecessary columns
data2 = data[:] # keeping a copy for later
#data.drop(['Unnamed: 0','Unnamed: 0.1','day','display_id','ad_id','landing_page','campaign_id','advertiser_id','uuid','document_id','source_id','geo_location'], axis=1, inplace=True)
data.drop(['Unnamed: 0','display_id','ad_id','uuid','document_id','platform','hour','topic_id'], axis=1, inplace=True)

In [4]:
data.T.apply(lambda x: x.nunique(), axis=1)

clicked            2
landing_page     501
campaign_id      501
advertiser_id    501
geo_location      55
day               14
category_id       21
entity_id         21
source_id         21
publisher_id      21
dtype: int64

In [5]:
# Converting to dummies
data = pd.get_dummies(data)

# Splitting into train and test

# X = data.ix[:, data.columns != 'clicked']
# y = data['clicked']
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X = data[:37003]
y = data[37003:]

X_train = X.ix[:, X.columns != 'clicked']
X_test = y.ix[:, y.columns != 'clicked']

y_train = X['clicked']
y_test = y['clicked']

print X_train.shape
print X_test.shape
print y_train.shape
print y_test.shape

(37003, 1656)
(14668, 1656)
(37003L,)
(14668L,)

In [6]:
X_train[:3]

,landing_page_1004113,landing_page_1009076,landing_page_1009078,landing_page_1012172,landing_page_1019158,landing_page_1019847,landing_page_1027503,landing_page_1031141,landing_page_1035304,landing_page_1043039,...,publisher_id_450.0,publisher_id_704.0,publisher_id_714.0,publisher_id_740.0,publisher_id_78.0,publisher_id_784.0,publisher_id_867.0,publisher_id_874.0,publisher_id_875.0,publisher_id_MinorityClass
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
data2[:20]

,Unnamed: 0,display_id,ad_id,clicked,landing_page,campaign_id,advertiser_id,uuid,document_id,platform,geo_location,day,hour,category_id,topic_id,entity_id,source_id,publisher_id
0,0,1459,132913,0,MinorityClass,MinorityClass,3074,faf57f287517f4,1649164,2,CA,2016-06-14,4,1610.0,16.0,MinorityClass,MinorityClass,MinorityClass
1,1,1459,176834,0,1145458,MinorityClass,2352,faf57f287517f4,1649164,2,CA,2016-06-14,4,1610.0,16.0,MinorityClass,MinorityClass,MinorityClass
2,2,1459,206927,1,MinorityClass,MinorityClass,2635,faf57f287517f4,1649164,2,CA,2016-06-14,4,1610.0,16.0,MinorityClass,MinorityClass,MinorityClass
3,3,1820,45305,0,MinorityClass,MinorityClass,1198,1f73468d752afe,1764575,2,IL,2016-06-14,4,1907.0,184.0,MinorityClass,MinorityClass,MinorityClass
4,4,1820,97384,1,MinorityClass,MinorityClass,1644,1f73468d752afe,1764575,2,IL,2016-06-14,4,1907.0,184.0,MinorityClass,MinorityClass,MinorityClass
5,5,1820,211049,0,1534322,24127,1863,1f73468d752afe,1764575,2,IL,2016-06-14,4,1907.0,184.0,MinorityClass,MinorityClass,MinorityClass
6,6,1820,250319,0,1592795,25645,2348,1f73468d752afe,1764575,2,IL,2016-06-14,4,1907.0,184.0,MinorityClass,MinorityClass,MinorityClass
7,7,2614,67347,0,942989,9029,92,2180e7affabb67,341873,3,OH,2016-06-14,4,1513.0,MinorityClass,Unknown,MinorityClass,MinorityClass
8,8,2614,144740,0,1337362,18488,2909,2180e7affabb67,341873,3,OH,2016-06-14,4,1513.0,MinorityClass,Unknown,MinorityClass,MinorityClass
9,9,2614,148962,0,1340766,MinorityClass,3016,2180e7affabb67,341873,3,OH,2016-06-14,4,1513.0,MinorityClass,Unknown,MinorityClass,MinorityClass
10,10,2614,173130,1,1302484,21210,2769,2180e7affabb67,341873,3,OH,2016-06-14,4,1513.0,MinorityClass,Unknown,MinorityClass,MinorityClass
11,11,3586,31279,1,MinorityClass,MinorityClass,535,f38a01c5e4a173,1044370,1,SC,2016-06-14,4,2100.0,MinorityClass,MinorityClass,7736.0,450.0
12,12,3586,34906,0,872063,MinorityClass,1650,f38a01c5e4a173,1044370,1,SC,2016-06-14,4,2100.0,MinorityClass,MinorityClass,7736.0,450.0
13,13,3586,37685,0,MinorityClass,MinorityClass,MinorityClass,f38a01c5e4a173,1044370,1,SC,2016-06-14,4,2100.0,MinorityClass,MinorityClass,7736.0,450.0
14,14,3586,153413,0,MinorityClass,MinorityClass,1913,f38a01c5e4a173,1044370,1,SC,2016-06-14,4,2100.0,MinorityClass,MinorityClass,7736.0,450.0
15,15,3586,153430,0,987161,19525,1913,f38a01c5e4a173,1044370,1,SC,2016-06-14,4,2100.0,MinorityClass,MinorityClass,7736.0,450.0
16,16,3586,235104,0,1587377,25526,2407,f38a01c5e4a173,1044370,1,SC,2016-06-14,4,2100.0,MinorityClass,MinorityClass,7736.0,450.0
17,17,5161,28346,1,MinorityClass,1423,308,cee8985b70130f,1409862,2,TX,2016-06-14,4,Unknown,MinorityClass,MinorityClass,MinorityClass,MinorityClass
18,18,5161,99277,0,MinorityClass,MinorityClass,2690,cee8985b70130f,1409862,2,TX,2016-06-14,4,Unknown,MinorityClass,MinorityClass,MinorityClass,MinorityClass
19,19,5161,125326,0,MinorityClass,MinorityClass,3001,cee8985b70130f,1409862,2,TX,2016-06-14,4,Unknown,MinorityClass,MinorityClass,MinorityClass,MinorityClass

In [8]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import (train_test_split,GridSearchCV)
from sklearn.metrics import (accuracy_score,roc_auc_score)
from sklearn.ensemble import (RandomForestClassifier)

In [9]:
# Random Forest
RFC = RandomForestClassifier()

In [173]:
param_grid = { 'n_estimators' : [10,15,17,19, 21,23,25,50,100,200], 'criterion' : ['gini', 'entropy'] }

def hypertuning(estimator, param_grid, x_train, y_train):
    #This function takes as input an estimator, parameter grid to tune, and the features and target variable
    # It returns the best score and best parameters of this estimaor from given possible params
    
    cv_estimator = GridSearchCV(estimator = estimator, param_grid=param_grid, cv=5)
    cv_estimator.fit(X_train, y_train)
    return cv_estimator.best_score_, cv_estimator.best_params_

hypertuning(RFC, param_grid, X_train, y_train)

(0.80025943842391156, {'criterion': 'entropy', 'n_estimators': 200})

In [10]:
RFC = RandomForestClassifier(criterion='entropy',n_estimators=200)
model = RFC.fit(X_train, y_train)

In [11]:
# Predict on test
predicted = model.predict(X_test)

In [12]:
predicted_prob = model.predict_proba(X_test)
print "predictions for classes:",model.classes_

# Getting prob of click
click_prob = predicted_prob[:,1]
click_prob[:10]

predictions for classes: [0 1]

array([ 0.28875   ,  0.20208333,  0.04      ,  0.225     ,  0.24      ,
        0.20141667,  0.055     ,  0.1675    ,  0.17      ,  0.09      ])

In [13]:
# MAP function
def apk(actual, predicted, k=12):
    if len(predicted)>k:
        predicted = predicted[:k]
    score = 0.0
    num_hits = 0.0
    for i,p in enumerate(predicted):
        if p in actual and p not in predicted[:i]:
            num_hits += 1.0
            score += num_hits / (i+1.0)
    if not actual:
        return 0.0
    return score / min(len(actual), k)

def mapk(actual, predicted, k=12):
    return np.mean([apk(a,p,k) for a,p in zip(actual, predicted)])

In [14]:
# Assigning probabilities to test
#test_index = X_test.index.values.tolist()

#test_fin = data2[data2.index.isin(test_index)]
test_fin = data2[37003:]
test_fin = test_fin[['display_id','ad_id','clicked']]
test_fin['predict'] = click_prob

# Sorting probability in descending order - test
test_fin = test_fin.sort_values(by=['display_id','predict'], ascending=[True, False])
test_fin2 = test_fin[['display_id','ad_id']].groupby('display_id')['ad_id'].agg(lambda col: ' '.join(map(str,col)))

# Sorting probability in descending order - real
real = test_fin.sort_values(by=['display_id','clicked'], ascending=[True, False])
real2 = real[['display_id','ad_id']].groupby('display_id')['ad_id'].agg(lambda col: ' '.join(map(str,col)))

# Check accuracy
print(mapk(real2,test_fin2))

0.56927955628

In [15]:
test_index_range = data2[37003:].groupby('display_id').count()['ad_id'].tolist()

start = 0
num = 0
map12 = 0
for p in test_index_range:
   end = start+p
   temp_pred = click_prob.tolist()[start:end]
   temp = pd.DataFrame(data2[37003:].reset_index().ix[start:end-1][['ad_id','clicked']]).copy().reset_index().drop('index',axis=1)
   df=pd.DataFrame(temp_pred,columns=['prob'])
   temp = pd.concat([temp,df],axis=1)
   temp2= temp.sort_values('prob',ascending=False).reset_index().drop('index',axis=1)
   index = temp2.ix[temp2['clicked']==1].index[0]
   map12 = map12+(1.0/(index+1))
   start = end
print map12/len(test_index_range)

0.569059686581

In [16]:
#test_fin['predict'] = click_prob
test_fin

       display_id   ad_id  clicked   predict
37003    12030830   39068        0  0.288750
37006    12030830  300898        0  0.225000
37004    12030830   80033        1  0.202083
37005    12030830  174547        0  0.040000
37007    12031067   12270        0  0.240000
37008    12031067   15007        0  0.201417
37011    12031067  162965        0  0.170000
37010    12031067   87000        1  0.167500
37012    12031067  164304        0  0.090000
37009    12031067   84937        0  0.055000
37015    12032719  233500        0  0.525000
37013    12032719  167457        0  0.255000
37016    12032719  418737        0  0.176667
37017    12032719  466189        1  0.157500
37018    12032719  469843        0  0.157500
37014    12032719  190216        0  0.045000
37021    12035906  104707        0  0.260000
37024    12035906  508124        0  0.210000
37019    12035906   23690        1  0.158000
37023    12035906  244979        0  0.130000
37022    12035906  189812        0  0.025000
37020    12035906   63889        0  0.010000
37027    12037983  116261        0  0.617500
37025    12037983   57969        0  0.141667
37031    12037983  371355        1  0.091667
37033    12037983  396884        0  0.057667
37032    12037983  379134        0  0.042500
37026    12037983   87514        0  0.042345
37030    12037983  156147        0  0.015000
37029    12037983  155781        0  0.007500
...           ...     ...      ...       ...
51642    16866563  224052        0  0.110000
51638    16866563   57791        0  0.090000
51641    16866563  190281        0  0.081750
51648    16870086  148264        1  0.507917
51647    16870086   92114        0  0.252500
51645    16870086   83658        0  0.180000
51649    16870086  497494        0  0.091250
51646    16870086   91879        0  0.057500
51644    16870086   12564        0  0.032500
51653    16872308  379324        0  0.294916
51652    16872308  197124        1  0.139833
51650    16872308  146552        0  0.025000
51651    16872308  175525        0  0.019167
51659    16873760  349398        0  0.148381
51662    16873760  504469        0  0.122083
51655    16873760  164755        0  0.118333
51660    16873760  417678        0  0.118333
51661    16873760  418988        0  0.118333
51656    16873760  169549        1  0.117083
51657    16873760  169855        0  0.104464
51658    16873760  245086        0  0.055417
51654    16873760   78848        0  0.045000
51663    16874399   56570        0  0.250888
51664    16874399   56634        1  0.250888
51665    16874399   56643        0  0.250888
51666    16874399   98952        0  0.250888
51670    16874399  491936        0  0.250888
51667    16874399  132019        0  0.232500
51669    16874399  220326        0  0.163363
51668    16874399  205277        0  0.035000

[14668 rows x 4 columns]

In [17]:
test_fin2[:20]

display_id
12030830                            39068 300898 80033 174547
12031067                12270 15007 162965 87000 164304 84937
12032719            233500 167457 418737 466189 469843 190216
12035906              104707 508124 23690 244979 189812 63889
12037983    116261 57969 371355 396884 379134 87514 156147...
12041370                    276904 207568 362107 470780 18353
12043632                           279807 223408 18922 506605
12044129                           220761 136102 88994 125693
12046132    107340 190281 371053 386922 173117 116386 1229...
12046358              99215 11498 357557 138532 123730 238222
12047798            142690 515377 199321 179318 238221 292461
12048542                                  87266 152193 294436
12050113                                        287157 418751
12051013                            29539 61159 470786 210005
12052473    280430 476018 407543 128326 128339 190817 4893...
12053070    198119 263810 198129 198151 157186 87380 50861...
12054282               347919 70529 232122 13500 135466 85830
12054988                                   41399 54030 141269
12055370                                   181548 64085 21457
12055472                            59943 153794 355712 72075
Name: ad_id, dtype: object

In [61]:
real2[:20]

display_id
12030830                            80033 39068 300898 174547
12031067                87000 12270 164304 162965 15007 84937
12032719            466189 233500 167457 418737 469843 190216
12035906              23690 104707 244979 189812 508124 63889
12037983    371355 116261 87514 57969 134979 379134 396884...
12041370                    276904 470780 362107 207568 18353
12043632                           18922 279807 223408 506605
12044129                           220761 136102 125693 88994
12046132    173117 107340 371053 190281 386922 116386 1229...
12046358              238222 357557 138532 99215 11498 123730
12047798            142690 515377 199321 179318 292461 238221
12048542                                  152193 87266 294436
12050113                                        287157 418751
12051013                            29539 470786 61159 210005
12052473    128326 476018 280430 407543 49770 128339 19081...
12053070    198129 198119 157186 263810 50861 87380 198151...
12054282               135466 347919 13500 70529 85830 232122
12054988                                   54030 41399 141269
12055370                                   181548 21457 64085
12055472                            153794 59943 355712 72075
Name: ad_id, dtype: object